modLoader="javafml"
loaderVersion="[34,)"

license="LGPL-3.0-only"
issueTrackerURL="https://github.com/ChampionAsh5357/Paranoia/issues"

[[mods]]
modId="paranoia"
version="${version}"
displayName="Paranoia"

# updateJSONURL=""
# displayURL=""
# logoFile=""

# credits=""
authors="\u00a7bChampionAsh5357"

description="
TODO.
"

[[dependencies.paranoia]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"    
[[dependencies.paranoia]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"